# Generated by Django 3.0.3 on 2023-07-15 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('description', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genus', models.CharField(max_length=127)),
                ('species', models.CharField(max_length=255)),
                ('clade', models.CharField(max_length=10)),
                ('taxa_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_id', models.CharField(default='', max_length=255)),
                ('domain_description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protein_id', models.CharField(max_length=255)),
                ('sequence', models.CharField(max_length=1024)),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProteinDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caller.Domain')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caller.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein',
            name='domains',
            field=models.ManyToManyField(related_name='domains', through='caller.ProteinDomains', to='caller.Domain'),
        ),
        migrations.AddField(
            model_name='protein',
            name='organism_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caller.Organism'),
        ),
        migrations.AddField(
            model_name='domain',
            name='pfam_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caller.Pfam'),
        ),
        migrations.AddField(
            model_name='domain',
            name='protein_id',
            field=models.ManyToManyField(related_name='protein', through='caller.ProteinDomains', to='caller.Protein'),
        ),
    ]
