# Generated by Django 3.0.3 on 2023-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfam',
            name='domain_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pfam',
            name='domain_id',
            field=models.CharField(max_length=255),
        ),
    ]
